export const COLLECTION_LAYOUT = {
  COLLECTION: 'COLLECTION',
  COLLECTION_GROUP: 'COLLECTION_GROUP'
}

export const COLLECTION_TYPE = {
  COMMON: 'COMMON',
  FLASH_SALE: 'FLASH_SALE',
  COLLECTION_GROUP: 'COLLECTION_GROUP'
}