export const HOME_SET_LOADING = 'HOME_SET_LOADING';
export const HOME_SET_MORE_LOADING = 'HOME_SET_LOADING';
export const HOME_SET_ERROR = 'HOME_SET_ERROR';
export const HOME_FETCH_SUCCESS = 'HOME_FETCH_SUCCESS';
export const HOME_FETCH_DATA = "HOME_FETCH_DATA"
export const HOME_FETCH_MORE_DATA = "HOME_FETCH_MORE_DATA"
export const HOME_FETCH_MORE_SUCCESS = "HOME_FETCH_MORE_SUCCESS"
export const HOME_SET_REFRESHING = "HOME_SET_REFRESHING"