export const HOME_SET_LOADING = 'HOME_SET_LOADING';
export const HOME_SET_ERROR = 'HOME_SET_ERROR';
export const HOME_FETCH_SUCCESS = 'HOME_FETCH_SUCCESS';
export const HOME_FETCH_DATA = "HOME_FETCH_DATA"